model:
  base_learning_rate: 4.5e-6
  target: specvqgan.models.vqgan.VQModel
  params:
    embed_dim: 256
    n_embed: 1024
    L: 2.0
    ddconfig:
      double_z: False
      z_channels: 256
      resolution: 160
      in_channels: 1
      out_ch: 1
      ch: 128
      ch_mult: [1, 1, 2, 2, 4]  # num_down = len(ch_mult)-1
      num_res_blocks: 2
      attn_resolutions: [10]
      dropout: 0.0

    lossconfig:
      target: specvqgan.modules.losses.vqperceptual.VQLPAPSWithDiscriminator
      params:
        disc_conditional: False
        disc_in_channels: 1
        disc_start: 30001
        disc_weight: 0.8
        codebook_weight: 1.0
        min_adapt_weight: 1.0
        max_adapt_weight: 1.0
        perceptual_weight: 1.0

lightning:
  callbacks:
    image_logger:
      target: train.ImageLogger
      params:
        epoch_frequency: 50
        for_specs: True
        vocoder_cfg:
          target: train.VocoderMelGan
          params:
            ckpt_vocoder: './vocoder/logs/vggsound/'
  trainer:
    sync_batchnorm: true
    max_epochs: 12000

data:
  target: train.ImpactSetWaveModuleFromConfig
  params:
    batch_size: 32
    num_workers: 16

    splits_path: './data'
    data_path: 'data/ImpactSet/impactset-proccess-resize'
    mel_num: 80
    spec_crop_len: 160
    L: 2.0
    sample_rate: 22050
    random_crop: False
    denoise: True

    train:
      target: specvqgan.data.impactset.ImpactSetWaveTrain
      params:
        specs_dataset_cfg:
    validation:
      target: specvqgan.data.impactset.ImpactSetWaveValidation
      params:
        specs_dataset_cfg:
    test:
      target: specvqgan.data.impactset.ImpactSetWaveTest
      params:
        specs_dataset_cfg:
